<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpbtpsz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpbtpsz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRpbtpsz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRpbtpsz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRpbtpsz\appProdProjectContainer(array(
    'container.build_hash' => 'Rpbtpsz',
    'container.build_id' => 'f48cc39e',
    'container.build_time' => 1545623984,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpbtpsz');
